codecov:
  require_ci_to_pass: true
  branch: master
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "5...100"
  status:
    patch: false
    project:
      default: false
      ui:
        target: 5%
        flags:
          - sbccommoncomponentsweb

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

flags:
  sbccommoncomponentsweb:
    paths:
      - vue/sbc-common-components/src
    carryforward: true
