name: NPM_PUBLISH

on:
  push:
    branches: master
    paths:
    - '**package.json'
  workflow_dispatch:

permissions:
  id-token: write # required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Update npm
      # This is critical. Older npm versions have a bug with subfolder OIDC.
      run: npm install -g npm@latest
    - name: npm publisher script
      working-directory: ./vue/sbc-common-components/
      run: |
        npm install
        npm run build
        npm publish --access public
